coverage:
  paths:
    - 'coverage/lcov_backend.info'
    - 'coverage/lcov_frontend.info'
codeToTestRatio:
  code:
    - 'backend/src/*.rs'
    - 'frontend/app/*.ts'
    - 'frontend/app/*.tsx'
    - '!**/*.d.ts'
    - '!**/*.test.tsx'
  test:
    - '**/*.test.tsx'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
